language: node_js
node_js:
  - 12
branches:
  only:
    - master
    - "/^v.*$/"
deploy:
  provider: npm
  email: romu@soundstep.com
  api_key:
    secure: H1FuaSSr1kHPZ128MbR3pfUU0QfbK4U42WmijkwZETVnbKIZw9aSiOskag3O84pvFAdNuFfgeJ55xxOerpaicWfT7m+44bGVuYCKZuCJfwe3ik/ZGheBac2bT04KxY/CWid81p1rTSTOvrYMScCnbSJpJ4c97jJ07Q8YF9XyMMddkcMsOUDBHhbCPTgWPenA+sM7P8Bu6g2++kGxm88g6fOKfN0zTxGWh5sCPUWlrB31Nj/sFQ0jRqcFqsslb957af1cypEhW1cmOcGk7qF+DHM9Sn6NfnyvJpITezwWNyLRFT664azN9lPUXqVK4t8s7bM/TKcJ0fSDbBbpEenAL8m1NUc4xp2tpU41SWBxGkNv11yxAcncjKdBQ1ewZNbsE6tb05rpYXiAHnxuFrC6BDXsH9dLNWzVbGYP4CF8AYU+En233yD07V6KoO8ZFJBFJZDBaOY1sXVXGTlOBODrP12QKk5Il9QnzWPR3v3MZJ026/4h7IRxE7JXxVVLzJvdvqsOpruzpOTqkp9mJZUniK96kOXFAuY9e16FtNw1/XsQGgCR+rk1hM9k1R83SsVOl1DaEy27ka3n2jJIXcTAviO0zH/GfvkO/PhlSbPKL9vLPneLGpGN0xmoSPOCvK5DWxWFcvhuzHxd4KAQBDppEXSYFF9jAWtnJafLZUF+apI=
  on:
    tags: true
    repo: soundstep/soma
